---
- name: Install locales
  apt: name={{ item }}
  with_items:
    - locales

- name: Generate locales
  locale_gen: name={{ item }} state=present
  with_items:
    - "de_DE.UTF-8"
    - "en_US.UTF-8"




