---
- hosts: all
  remote_user: root
  roles:
    - base
    - swarm
  vars_prompt:

    - name: "jenkins_username"
      prompt: "Enter Jenkins username"
      private: no

    - name: "jenkins_password"
      prompt: "Enter Jenkins password"
      private: yes

- hosts: slave
  remote_user: root
  roles:
    - jnv.debian-backports
    - jsunit
    - oracle_instant_client
    - docker
    - php-build
    - php
    - translation-sync
