---
- name: update packages cache
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  apt: name={{ item }}
  with_items:
    - ant
    - curl
    - docker.io
    - wget
    - mysql-server
    - postgresql
    - php5
    - php5-curl
    - php5-gd
    - php5-intl
    - php5-json
    - php5-mcrypt
    - php5-sqlite
    - php5-mysqlnd
    - php5-pgsql
    - php5-ldap
    - php5-dev
    - smbclient

  - name: install packages for phpenv
    apt: name={{ item }}
    with_items:
       - libxml2-dev
       - re2c
       - libmcrypt-dev
       - libcurl3-openssl-dev
       - bison
       - flex
       - libjpeg-dev
       - libpng-dev
       - libtidy-dev
       - libxslt-dev
       - libreadline-dev
       - libldap2-dev
       - libpq-dev
       - libbz2-dev
       - libicu-dev
       - libircclient-dev
       - libmysqlclient-dev

  - name: install phunit
    get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=555

  - name: install composer
    get_url: url=https://getcomposer.org/download/1.1.0-RC/composer.phar  dest=/usr/local/bin checksum=sha256:31e771ed24f3db45019a073fe9e43a6a8e75249962012955cd105ebec0a08100

#  - name: download phpenv
#    get_url: url=https://raw.github.com/CHH/phpenv/master/bin/phpenv-install.sh dest=/home/jenkins
#    become: yes
#    become_user: jenkins
#
#  - name: install phpenv
#    shell: /home/jenkins/phpenv-install.sh
#    args:
#      chdir: /home/jenkins
#      executable: /bin/bash
#    become: yes
#    become_user: jenkins
#    become_method: su

#  mkdir /home/vagrant/.phpenv/plugins
#  cd /home/vagrant/.phpenv/plugins && git clone git://github.com/CHH/php-build.git
#  echo 'PATH=$HOME/.phpenv/bin:$PATH # Add phpenv to PATH for scripting' >> /home/vagrant/.bashrc
#  echo 'eval "$(phpenv init -)"' >> /home/vagrant/.bashrc

